  version: '3.7'

  services:
    db:
      image: postgres:12-alpine
      ports:
        - "5432:5432"
      env_file:
        - ./.env-docker
      expose:
        - "5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - static_volume:/app/staticfiles
      ports:
        - "8000:8000"
      expose:
        - 8000
      depends_on:
        - db
      env_file:
        - ./.env-docker
      entrypoint:
        - "./docker-entrypoint.sh"

  volumes:
    postgres_data:
    static_volume:
    code:
