# Generated by Django 3.2.5 on 2021-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacaoAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('mensagem', models.TextField()),
                ('via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('para', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('ENVIADA', 'Enviada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10)),
            ],
            options={
                'unique_together': {('data', 'mensagem', 'via', 'para', 'status')},
            },
        ),
    ]
